<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $blogs = array(
            array('title'=>'Organizujte svoj radni prostor', 
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ornare tellus a tempus interdum. Nullam nec pellentesque sem. Maecenas at odio sit amet purus facilisis sodales. Suspendisse eget justo fringilla, aliquam tellus in, scelerisque nisi. Donec efficitur porttitor lectus a scelerisque. Duis sed ipsum id eros ornare molestie. Suspendisse vulputate, turpis eu blandit sodales, dolor dolor fringilla arcu, sed posuere est lorem vitae turpis. Mauris turpis lacus, imperdiet vitae magna ac, blandit feugiat augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam aliquam massa vitae bibendum porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vulputate lorem massa, ut maximus tellus commodo tempor. Vivamus placerat nec elit at tristique. Quisque felis tortor, porttitor quis pulvinar vitae, blandit et orci. Quisque eget molestie augue, sit amet convallis lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
            Aliquam aliquam turpis diam, in sagittis nisi mattis eu. Sed at tristique magna, sit amet scelerisque orci. Etiam facilisis ex vitae tortor ultricies eleifend. Nam id elit euismod, volutpat lorem a, tristique nisi. Quisque tristique elit dolor, ac varius velit malesuada eu. Donec eu massa dignissim, luctus erat vel, blandit enim. Aliquam justo ligula, fringilla ac purus ut, aliquet sagittis sapien. Fusce auctor lacus at lectus malesuada pulvinar. Sed dignissim feugiat purus vestibulum hendrerit. Sed non purus placerat odio ultricies molestie nec in massa. Sed vitae ultricies leo. In hac habitasse platea dictumst. Quisque purus nulla, pellentesque sed imperdiet id, malesuada pharetra metus. Sed aliquam vestibulum ex eget consequat. Mauris tempus ligula ut ipsum maximus, ac tempor odio dignissim.            
            Nunc sed imperdiet erat, et congue magna. Maecenas id pellentesque dui. Suspendisse potenti. Curabitur commodo nibh nec ex ultricies dignissim. Sed est nulla, iaculis in ultricies vitae, tincidunt ut purus. Nulla facilisi. Suspendisse imperdiet, ante vitae rutrum lacinia, risus velit euismod turpis, sit amet maximus arcu lorem eu justo. Nunc eget malesuada metus. Nullam a scelerisque nibh. Aenean dignissim odio eget neque tincidunt, ac pellentesque erat maximus. Praesent vitae ornare magna. Nullam a fermentum turpis, sed suscipit enim. Vestibulum feugiat risus urna, et iaculis nisl sagittis ac. Donec eleifend pellentesque porttitor.           
            Fusce vestibulum lobortis velit in blandit. Morbi suscipit magna lacus, non euismod ante pulvinar auctor. Nullam id maximus nunc. Etiam tincidunt suscipit lacus vel semper. Donec viverra urna et augue sodales fringilla. Ut hendrerit felis ut ex feugiat eleifend. Donec a magna et elit porta laoreet. Nam ut felis ut ex aliquet porta nec nec dolor. Cras sed dignissim massa. Sed aliquam nec nunc in laoreet. Quisque risus sapien, viverra id vehicula eget, tincidunt eget eros. Donec in convallis enim. Pellentesque id massa et tellus facilisis fringilla. Integer lobortis velit a interdum tincidunt. Mauris neque nulla, blandit eget lobortis eget, molestie ac orci.',
            'img' => '../img/blog1.jfif', 'created_by' => 'Menadzer Menadzer'),
            array('title'=>'Malim uredjajima napravite velike korake', 
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ornare tellus a tempus interdum. Nullam nec pellentesque sem. Maecenas at odio sit amet purus facilisis sodales. Suspendisse eget justo fringilla, aliquam tellus in, scelerisque nisi. Donec efficitur porttitor lectus a scelerisque. Duis sed ipsum id eros ornare molestie. Suspendisse vulputate, turpis eu blandit sodales, dolor dolor fringilla arcu, sed posuere est lorem vitae turpis. Mauris turpis lacus, imperdiet vitae magna ac, blandit feugiat augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam aliquam massa vitae bibendum porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vulputate lorem massa, ut maximus tellus commodo tempor. Vivamus placerat nec elit at tristique. Quisque felis tortor, porttitor quis pulvinar vitae, blandit et orci. Quisque eget molestie augue, sit amet convallis lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
            Aliquam aliquam turpis diam, in sagittis nisi mattis eu. Sed at tristique magna, sit amet scelerisque orci. Etiam facilisis ex vitae tortor ultricies eleifend. Nam id elit euismod, volutpat lorem a, tristique nisi. Quisque tristique elit dolor, ac varius velit malesuada eu. Donec eu massa dignissim, luctus erat vel, blandit enim. Aliquam justo ligula, fringilla ac purus ut, aliquet sagittis sapien. Fusce auctor lacus at lectus malesuada pulvinar. Sed dignissim feugiat purus vestibulum hendrerit. Sed non purus placerat odio ultricies molestie nec in massa. Sed vitae ultricies leo. In hac habitasse platea dictumst. Quisque purus nulla, pellentesque sed imperdiet id, malesuada pharetra metus. Sed aliquam vestibulum ex eget consequat. Mauris tempus ligula ut ipsum maximus, ac tempor odio dignissim.            
            Nunc sed imperdiet erat, et congue magna. Maecenas id pellentesque dui. Suspendisse potenti. Curabitur commodo nibh nec ex ultricies dignissim. Sed est nulla, iaculis in ultricies vitae, tincidunt ut purus. Nulla facilisi. Suspendisse imperdiet, ante vitae rutrum lacinia, risus velit euismod turpis, sit amet maximus arcu lorem eu justo. Nunc eget malesuada metus. Nullam a scelerisque nibh. Aenean dignissim odio eget neque tincidunt, ac pellentesque erat maximus. Praesent vitae ornare magna. Nullam a fermentum turpis, sed suscipit enim. Vestibulum feugiat risus urna, et iaculis nisl sagittis ac. Donec eleifend pellentesque porttitor.           
            Fusce vestibulum lobortis velit in blandit. Morbi suscipit magna lacus, non euismod ante pulvinar auctor. Nullam id maximus nunc. Etiam tincidunt suscipit lacus vel semper. Donec viverra urna et augue sodales fringilla. Ut hendrerit felis ut ex feugiat eleifend. Donec a magna et elit porta laoreet. Nam ut felis ut ex aliquet porta nec nec dolor. Cras sed dignissim massa. Sed aliquam nec nunc in laoreet. Quisque risus sapien, viverra id vehicula eget, tincidunt eget eros. Donec in convallis enim. Pellentesque id massa et tellus facilisis fringilla. Integer lobortis velit a interdum tincidunt. Mauris neque nulla, blandit eget lobortis eget, molestie ac orci.',
            'img' => '../img/blog2.jfif', 'created_by' => 'Menadzer Menadzer'),
            array('title'=>'Uvek nadjite vreme za zabavu', 
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ornare tellus a tempus interdum. Nullam nec pellentesque sem. Maecenas at odio sit amet purus facilisis sodales. Suspendisse eget justo fringilla, aliquam tellus in, scelerisque nisi. Donec efficitur porttitor lectus a scelerisque. Duis sed ipsum id eros ornare molestie. Suspendisse vulputate, turpis eu blandit sodales, dolor dolor fringilla arcu, sed posuere est lorem vitae turpis. Mauris turpis lacus, imperdiet vitae magna ac, blandit feugiat augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam aliquam massa vitae bibendum porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vulputate lorem massa, ut maximus tellus commodo tempor. Vivamus placerat nec elit at tristique. Quisque felis tortor, porttitor quis pulvinar vitae, blandit et orci. Quisque eget molestie augue, sit amet convallis lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
            Aliquam aliquam turpis diam, in sagittis nisi mattis eu. Sed at tristique magna, sit amet scelerisque orci. Etiam facilisis ex vitae tortor ultricies eleifend. Nam id elit euismod, volutpat lorem a, tristique nisi. Quisque tristique elit dolor, ac varius velit malesuada eu. Donec eu massa dignissim, luctus erat vel, blandit enim. Aliquam justo ligula, fringilla ac purus ut, aliquet sagittis sapien. Fusce auctor lacus at lectus malesuada pulvinar. Sed dignissim feugiat purus vestibulum hendrerit. Sed non purus placerat odio ultricies molestie nec in massa. Sed vitae ultricies leo. In hac habitasse platea dictumst. Quisque purus nulla, pellentesque sed imperdiet id, malesuada pharetra metus. Sed aliquam vestibulum ex eget consequat. Mauris tempus ligula ut ipsum maximus, ac tempor odio dignissim.            
            Nunc sed imperdiet erat, et congue magna. Maecenas id pellentesque dui. Suspendisse potenti. Curabitur commodo nibh nec ex ultricies dignissim. Sed est nulla, iaculis in ultricies vitae, tincidunt ut purus. Nulla facilisi. Suspendisse imperdiet, ante vitae rutrum lacinia, risus velit euismod turpis, sit amet maximus arcu lorem eu justo. Nunc eget malesuada metus. Nullam a scelerisque nibh. Aenean dignissim odio eget neque tincidunt, ac pellentesque erat maximus. Praesent vitae ornare magna. Nullam a fermentum turpis, sed suscipit enim. Vestibulum feugiat risus urna, et iaculis nisl sagittis ac. Donec eleifend pellentesque porttitor.           
            Fusce vestibulum lobortis velit in blandit. Morbi suscipit magna lacus, non euismod ante pulvinar auctor. Nullam id maximus nunc. Etiam tincidunt suscipit lacus vel semper. Donec viverra urna et augue sodales fringilla. Ut hendrerit felis ut ex feugiat eleifend. Donec a magna et elit porta laoreet. Nam ut felis ut ex aliquet porta nec nec dolor. Cras sed dignissim massa. Sed aliquam nec nunc in laoreet. Quisque risus sapien, viverra id vehicula eget, tincidunt eget eros. Donec in convallis enim. Pellentesque id massa et tellus facilisis fringilla. Integer lobortis velit a interdum tincidunt. Mauris neque nulla, blandit eget lobortis eget, molestie ac orci.',
            'img' => '../img/home4.jfif', 'created_by' => 'Menadzer Menadzer'),
            array('title'=>'Nikad nije bilo lakse postati milioner nego danas', 
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ornare tellus a tempus interdum. Nullam nec pellentesque sem. Maecenas at odio sit amet purus facilisis sodales. Suspendisse eget justo fringilla, aliquam tellus in, scelerisque nisi. Donec efficitur porttitor lectus a scelerisque. Duis sed ipsum id eros ornare molestie. Suspendisse vulputate, turpis eu blandit sodales, dolor dolor fringilla arcu, sed posuere est lorem vitae turpis. Mauris turpis lacus, imperdiet vitae magna ac, blandit feugiat augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam aliquam massa vitae bibendum porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vulputate lorem massa, ut maximus tellus commodo tempor. Vivamus placerat nec elit at tristique. Quisque felis tortor, porttitor quis pulvinar vitae, blandit et orci. Quisque eget molestie augue, sit amet convallis lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
            Aliquam aliquam turpis diam, in sagittis nisi mattis eu. Sed at tristique magna, sit amet scelerisque orci. Etiam facilisis ex vitae tortor ultricies eleifend. Nam id elit euismod, volutpat lorem a, tristique nisi. Quisque tristique elit dolor, ac varius velit malesuada eu. Donec eu massa dignissim, luctus erat vel, blandit enim. Aliquam justo ligula, fringilla ac purus ut, aliquet sagittis sapien. Fusce auctor lacus at lectus malesuada pulvinar. Sed dignissim feugiat purus vestibulum hendrerit. Sed non purus placerat odio ultricies molestie nec in massa. Sed vitae ultricies leo. In hac habitasse platea dictumst. Quisque purus nulla, pellentesque sed imperdiet id, malesuada pharetra metus. Sed aliquam vestibulum ex eget consequat. Mauris tempus ligula ut ipsum maximus, ac tempor odio dignissim.            
            Nunc sed imperdiet erat, et congue magna. Maecenas id pellentesque dui. Suspendisse potenti. Curabitur commodo nibh nec ex ultricies dignissim. Sed est nulla, iaculis in ultricies vitae, tincidunt ut purus. Nulla facilisi. Suspendisse imperdiet, ante vitae rutrum lacinia, risus velit euismod turpis, sit amet maximus arcu lorem eu justo. Nunc eget malesuada metus. Nullam a scelerisque nibh. Aenean dignissim odio eget neque tincidunt, ac pellentesque erat maximus. Praesent vitae ornare magna. Nullam a fermentum turpis, sed suscipit enim. Vestibulum feugiat risus urna, et iaculis nisl sagittis ac. Donec eleifend pellentesque porttitor.           
            Fusce vestibulum lobortis velit in blandit. Morbi suscipit magna lacus, non euismod ante pulvinar auctor. Nullam id maximus nunc. Etiam tincidunt suscipit lacus vel semper. Donec viverra urna et augue sodales fringilla. Ut hendrerit felis ut ex feugiat eleifend. Donec a magna et elit porta laoreet. Nam ut felis ut ex aliquet porta nec nec dolor. Cras sed dignissim massa. Sed aliquam nec nunc in laoreet. Quisque risus sapien, viverra id vehicula eget, tincidunt eget eros. Donec in convallis enim. Pellentesque id massa et tellus facilisis fringilla. Integer lobortis velit a interdum tincidunt. Mauris neque nulla, blandit eget lobortis eget, molestie ac orci.',
            'img' => '../img/home2.jfif', 'created_by' => 'Menadzer Menadzer'),
            
            
        );

        DB::table('blogs')->insert($blogs);
    }
}
